---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a Pull Request if any images can be compressed.
name: Compress Images on Demand

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '00 23 * * 0'

jobs:
  CompressOnDemandOrSchedule:
    name: calibreapp/image-actions

    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@f32575787d333b0579f0b7d506ff03be63a669d1 # 1.4.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: Compressed Images Nightly
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
