---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Lint

on:
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  lint:
    name: PR Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: PR Lint
        uses: ivuorinen/actions/pr-lint@0795e029fb0083fe692fb10b4ed6132822b069e6 # v2026.04.06
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
