---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

env:
  MAIN_BRANCH: main

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [master, main]
  workflow_call:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.nvmrc'

      - name: Cache Node Modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm packages
        run: npm install

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7
        env:
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: '${DEFAULT_WORKSPACE}'
          VALIDATE_JSON: false # doesn't handle new config format
          VALIDATE_NATURAL_LANGUAGE: false # doesn't seem to respect configs
          FIX_ANSIBLE: true
          FIX_ENV: true
          FIX_JSON_PRETTIER: true
          FIX_JSONC_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_SHELL_SHFMT: true
          FIX_TYPESCRIPT_PRETTIER: true
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: ${{ env.MAIN_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
