---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Lint

on:
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  lint:
    name: PR Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: PR Lint
        uses: ivuorinen/actions/pr-lint@6a8c40d9c5ff01b901d382b0ef86d432215aae2a # v2026.09.09
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
