---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Lint

on:
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  lint:
    name: PR Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: PR Lint
        uses: ivuorinen/actions/pr-lint@6e8f2aae9d0846d901d9eba15b8e94a2900573dc # v2026.03.02
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
