---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: readme-scribe

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'main'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: 'Update generated README'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
