name: readme-scribe

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"
  push:
    branches:
      - "main"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Update generated README"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
