---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: readme-scribe

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'main'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'Update generated README'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
