---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Drafter

on:
  workflow_call:

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
