---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Drafter

on:
  workflow_call:

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
