---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Drafter

on:
  workflow_call:

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
