---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reviewdog Linters

on: [pull_request, workflow_call]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: GitHub Actions
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@ec0dde52d1644e27666856474a8cbc86032dcb8d # v0.29.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: markdownlint
        uses: reviewdog/action-markdownlint@6f0e0e8703a9e840ffefa37a2775832c51c1c640 # v0.28.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: shfmt
        uses: reviewdog/action-shfmt@c5e3ba7497c338866921924691aef4fa18bc1fe0 # v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: |
            --find
            --list
            --write
            --diff
            --language-dialect bash
            --indent 2
            --binary-next-line
            --case-indent
            --space-redirects
            --func-next-line

      - name: yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
