---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reviewdog Linters

on: [pull_request, workflow_call]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: GitHub Actions
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@53b50179462bbe04af2f25f088b97e55e1dec3a1 # v0.29.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: markdownlint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0.26.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: shfmt
        uses: reviewdog/action-shfmt@d8f080930b9be5847b4f97e9f4122b81a82aaeac # v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: |
            --find
            --list
            --write
            --diff
            --language-dialect bash
            --indent 2
            --binary-next-line
            --case-indent
            --space-redirects
            --func-next-line

      - name: yamllint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
